### ISSUE TITLE
Connect / Assembly new sensors

### ISSUE THREAD

**Issue by dandrits** [maellak/DIYiotCar#16]
Connect to car via existing/new arduinos / arduino two new sensors: one more sonar and a 9DOF IMU

**Comment by datapack** [comment]
Μιχαήλ    Βίτκος

**Comment by datapack** [comment]
Βασίλης  Χασιώτης

**Comment by datapack** [comment]
ΞΕΝΟΦΩΝ ΚΕΚΑΤΟΣ

**Comment by datapack** [comment]
Αθανάσιος Αγραφιώτης

**Comment by datapack** [comment]
ΧΡΗΣΤΟΣ ΠΑΠΑΓΙΑΝΝΗΣ

**Comment by datapack** [comment]
ΓΕΩΡΓΙΟΣ ΤΣΙΦΕΤΑΚΗΣ

**Comment by datapack** [comment]
ΙΩΑΝΝΗΣ ΚΑΡΑΧΑΛΙΟΣ

**Comment by datapack** [comment]
ΗΛΙΑΣ ΝΑΤΣΙΟΠΟΥΛΟΣ

**Comment by datapack** [comment]
Μιχαήλ Γαλλιάκης

**Comment by datapack** [comment]
Ηλίας Κόκκινος

**Comment by datapack** [comment]
ΜΑΡΙΟΣ ΛΑΖΟΣ

**Comment by datapack** [comment]
ΜΙΧΑΛΗΣ ΒΑΜΒΑΚΑΡΗΣ
