### ISSUE TITLE
Create sketch for IMU

### ISSUE THREAD

**Issue by dandrits** [maellak/DIYiotCar#17]
Create a sketch for LSM9DS0 9DOF Sparkfun's IMU for a new arduino. The sketch should provide movement/position data to openwrt and raspberry pi

**Comment by datapack** [comment]
ΙΩΑΝΝΗΣ  ΚΑΡΑΧΑΛΙΟΣ

**Comment by datapack** [comment]
ΗΛΙΑΣ	ΝΑΤΣΙΟΠΟΥΛΟΣ

**Comment by datapack** [comment]
Μιχαήλ    Γαλλιάκης

**Comment by datapack** [comment]
Βασίλης  Χασιώτης

**Comment by datapack** [comment]
Ηλίας  Κόκκινος

**Comment by datapack** [comment]
ΜΑΡΙΟΣ    ΛΑΖΟΣ

**Comment by datapack** [comment]
ΜΙΧΑΛΗΣ	ΒΑΜΒΑΚΑΡΗΣ

**Comment by dandrits** [comment]
ΠΑΠΑΓΙΑΝΝΗΣ ΧΡΗΣΤΟΣ

**Comment by dandrits** [comment]
ΑΓΡΑΦΙΩΤΗΣ ΑΘΑΝΑΣΙΟΣ

**Comment by dandrits** [comment]
ΚΕΚΑΤΟΣ ΞΕΝΟΦΩΝ
