### ISSUE TITLE
Update sketch of sonars

### ISSUE THREAD

**Issue by dandrits** [maellak/DIYiotCar#18]
Update existing sketch of sonars/ir distance sensors and temp sensor by adding one more sonar

**Comment by datapack** [comment]
Μιχαήλ	Βίτκος

**Comment by datapack** [comment]
ΞΕΝΟΦΩΝ  ΚΕΚΑΤΟΣ

**Comment by datapack** [comment]
Αθανάσιος  Αγραφιώτης

**Comment by datapack** [comment]
ΧΡΗΣΤΟΣ  ΠΑΠΑΓΙΑΝΝΗΣ

**Comment by datapack** [comment]
ΓΕΩΡΓΙΟΣ    ΤΣΙΦΕΤΑΚΗΣ
