### ISSUE TITLE
Update php driving script

### ISSUE THREAD

**Issue by dandrits** [maellak/DIYiotCar#19]
Include data from one additional sonar and one 9DOF IMU to already existing data and combine them in order to upgrade a php's self driving script

**Comment by datapack** [comment]
Χαράλαμπος    Βιτώρος

**Comment by datapack** [comment]
ΒΑΣΙΛΕΙΟΣ  ΜΙΡΟΝΕΝΚΟ

**Comment by datapack** [comment]
Σταύρος Νιάφας
