### ISSUE TITLE
Update mapping on the web

### ISSUE THREAD

**Issue by dandrits** [maellak/DIYiotCar#21]
Use existing infrastructure and send real data to server and create maps

**Comment by datapack** [comment]
Γρηγόριος  Μπούρας

**Comment by datapack** [comment]
ΔΗΜΗΤΡΗΣ    ΜΠΟΥΡΟΥΣΗΣ

**Comment by datapack** [comment]
Αντώνης  Πέτρου

**Comment by datapack** [comment]
Αλέξανδρος    Δημητρίου

**Comment by datapack** [comment]
ΒΑΣΙΛΕΙΟΣ	ΜΙΡΟΝΕΝΚΟ

**Comment by dandrits** [comment]
Κωνσταντίνος Δεμερτζίδης
