### ISSUE TITLE
Login Issues (Web-inteface)

### ISSUE THREAD

**Issue by datapack** [maellak/DIYiotCar#24]
Fix login issues and landing page (web-interface )

**Comment by datapack** [comment]
ΚΩΝΣΤΑΝΤΙΝΟΣ    ΔΕΜΕΡΤΖΙΔΗΣ

**Comment by datapack** [comment]
Γρηγόριος  Μπούρας

**Comment by datapack** [comment]
ΔΗΜΗΤΡΗΣ    ΜΠΟΥΡΟΥΣΗΣ

**Comment by datapack** [comment]
Αντώνης  Πέτρου

**Comment by kgournakis** [comment]
Κωνσταντίνος Γουρνάκης

**Comment by dandrits** [comment]
Αλέξανδρος Δημητρίου
